### ISSUE TITLE
Unable to run on Linux

### ISSUE THREAD

**Issue by manfromarce** [congzhangzh/desktoploveblazorweb#12]
I tried to run the sample project on Linux (latest Kubuntu LTS) and I get the following exception:

```
Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPhotino.Native: cannot open shared object file: No such file or directory
   at PhotinoNET.PhotinoWindow.Photino_ctor(PhotinoNativeParameters& parameters)
   at PhotinoNET.PhotinoWindow.<WaitForClose>b__229_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow.WaitForClose()
Error #0
Unhandled exception. System.AggregateException: One or more errors occurred. (Native code exception. Error # 0  See inner exception for details.)
 ---> System.ApplicationException: Native code exception. Error # 0  See inner exception for details.
 ---> System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPhotino.Native: cannot open shared object file: No such file or directory
   at PhotinoNET.PhotinoWindow.Photino_ctor(PhotinoNativeParameters& parameters)
   at PhotinoNET.PhotinoWindow.<WaitForClose>b__229_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow.WaitForClose()
   --- End of inner exception stack trace ---
   at PhotinoNET.PhotinoWindow.WaitForClose()
   at BlazorBrowserNativeStyle.Program.OpenInLine(String address) in /home/manfredi/Scrivania/desktoploveblazorweb/BlazorBrowserNativeStyle/Program.cs:line 110
   at BlazorBrowserNativeStyle.Program.MainImpl(String[] args) in /home/manfredi/Scrivania/desktoploveblazorweb/BlazorBrowserNativeStyle/Program.cs:line 57
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BlazorBrowserNativeStyle.Program.Main(String[] args) in /home/manfredi/Scrivania/desktoploveblazorweb/BlazorBrowserNativeStyle/Program.cs:line 26

```
The dotnet build command is successful, the exception only occurs when running.
Everything works fine on Windows instead.

**Comment by congzhangzh** [comment]
It works well on my Debian Linux, it seems your native library load failed.

As the native part depends on [WebKitGTK+2](https://webkitgtk.org/) for Linux, have you installed it? 

maybe Kubuntu does not install it by default, install it by:

```bash
#aptitude search libwebkit2gtk
sudo apt install libwebkit2gtk-${your_version}
```

refs:
1. https://docs.tryphotino.io/Photino-Native

**Comment by manfromarce** [comment]
Thank you for your help, it works well now with libwebkit2gtk-4.0-37.
I had libwebkit2gtk-4.1-0 installed before and I thought it was fine but for some reason it didn't work.
